version: '3.8'

services:
  quality-check:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - hf_token
    ports: 
      - "8080:80"
    secrets:
      - hf_token
secrets:
  hf_token:
    file: .env/hf_token.txt
