name: Python Code Quality Checks
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "feature*" ]
    paths:
      - 'python/**'

jobs:
  pre-commit:
    if: '!cancelled()'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: cd python && poetry install
      - uses: pre-commit/action@v3.0.1
